services:
  - type: web
    name: money-journal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false # You will provide your MongoDB Atlas URI in the Render Dashboard
      - key: PORT
        value: 10000
